algoritmo "semnome"
var
 nome: caractere
 salario: real

inicio

      escreva("Digite o nome do funcionário: ")
      leia (nome)
      escreva("Digite o valor do salário no mês de Junho: ")
      leia(salario)
      
      escreval("Nome do funcionário: ", nome)
      escreval("Salário: R$", salario)
      escreval("O funcionário ", nome, " tem um salário de R$", salario, " em Junho")

fimalgoritmo